[package]
name = "slippi-stats-api"
version = "0.1.0"
authors = ["Max Timkovich <max@timkovi.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
peppi = { git = "https://github.com/hohav/peppi" }
rayon = "1.5.0"
walkdir = "2.3.2"
