[package]
name = "slippi-stats"
version = "0.1.0"
authors = ["Max Timkovich <max@timkovi.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peppi = { git = "https://github.com/hohav/peppi" }
